### ISSUE TITLE
Question: builddate = 1527355008 ?

### ISSUE THREAD

**Issue by Sami32** [gino0631/pac#4]
From today 26 may 2018 at around 19H13 GMT+1

What is the meaning of this builddate number found in `PKGINFO`?

**Comment by Sami32** [comment]
`builddate = $(date -u '+%s')`

**Comment by gino0631** [comment]
Epoch second, in other words: https://www.epochconverter.com

**Comment by Sami32** [comment]
Thank you for having shared your knowledge 👍
