### ISSUE TITLE
Permissions not set correctly on Linux

### ISSUE THREAD

**Issue by Sami32** [gino0631/pac#5]
It work correctly under Windows and macOS though.

- 0755 permission setting for _*.sh_ files doesn't work on Linux and the permission stay at 0644

```
					<plugin>
						<groupId>com.github.gino0631</groupId>
						<artifactId>pac-maven-plugin</artifactId>
						<version>1.0</version>
						<executions>
							<execution>
								<id>create-arch-package</id>
								<phase>package</phase>
								<goals>
									<goal>package</goal>
								</goals>
								<configuration>
									<root>${project.build.directory}/archlinux</root>
									<buildDirectory/>
									<outputFile>${project.artifactId}-${project.version}.any.pkg.tar.xz</outputFile>
									<packageName>${project.artifactId}</packageName>
									<packageVersion/> <!-- https://github.com/gino0631/pac/issues/2 -->
									<releaseNumber>1</releaseNumber>
									<architecture>any</architecture>
									<description>DLNA Media server</description>
									<url>https://www.digitalmediaserver.com</url>
									<packager>Not Me &lt;notme@unknown.com&gt;</packager>
									<licenses>
										<license>GPLv2+</license>
									</licenses>
									<permissionSets>
										<permissionSet>
											<includes>
												<include>**/*.sh</include>
											</includes>
											<fileMode>0755</fileMode>
										</permissionSet>
									</permissionSets>
									<entries>
										<symlink>
											<name>/usr/bin/${project.artifactId}</name>
											<linkTo>/opt/${project.name.camel}/${project.artifactId}.sh</linkTo>
										</symlink>
										<symlink>
											<name>/usr/bin/${project.name.short}</name>
											<linkTo>/opt/${project.name.camel}/${project.artifactId}.sh</linkTo>
										</symlink>
									</entries>
									<installScript>${project.build.directory}/install</installScript>
```

**Comment by Sami32** [comment]
In case the plugin has only be done for your specific use case i've also tried `**/*.sh` without more success on Linux.
Same result using a relative or absolute path.

**Comment by gino0631** [comment]
`permissionSets/permissionSet/includes/include` follow the same `fileSet` logic, so to match `*.sh` files in any directory the pattern `**/*.sh` has to be used.

If it still does not work, then 1) are you able to reproduce the same problem with [this sample project](https://github.com/gino0631/pac/tree/master/pac-maven-plugin/src/test/resources), 2) which version of Maven are you using?

**Comment by Sami32** [comment]
You've pointed me in the right direction, as i didn't thought about Maven as the "cause" of this issue 👍 

Maven 3.5.3 on Windows and Maven 3.3.9 on macOS where it work as expected.
Maven 3.5.2 on ArchLinux, Fedora where it doesn't set the permissions correctly.
Maven 3.3.9 on Ubuntu where it work as expected.

Is that possible to make it work with the newest Maven version without loosing the ability to use the older ones?

**Note**:
By now `permissionSets` is ignored when using newest _Maven_ version.

**Comment by Sami32** [comment]
Hum...now i got it working on all the Linux/Maven.
I don't really understand what happened, so i apology for the noise :/
