### ISSUE TITLE
Recommended "source" and "validpgpkeys" variables

### ISSUE THREAD

**Issue by Sami32** [gino0631/pac#6]
https://wiki.archlinux.org/index.php/PKGBUILD#source
https://wiki.archlinux.org/index.php/PKGBUILD#validpgpkeys

I just read that they are recommended variables to be set to be able to be on their official repositories.

**Comment by Sami32** [comment]
`validpgpkeys` could be handy when user want install the package directly from the project owner:
`sudo pacman -U https://github.com/.../MyApp-3.5.7-1-any.pkg.tar.xz`

Because this process need to verify the signature. And using this variable should be very handy IMO.

>  If used the upstream source likely provides the signing files (usually with the .asc or .sig file extensions), which must be specified in the source array.

**Comment by gino0631** [comment]
These are used when building packages from upstream sources (and verifying their signatures). Since we are not doing that, these variables are just not relevant.
