### ISSUE TITLE
<packageVersion> should be automatically converted to lower case

### ISSUE THREAD

**Issue by Sami32** [gino0631/pac#7]
`packageVersion` should be automatically converted to lower case to make the build compliant with the Arch package requirement.
https://wiki.archlinux.org/index.php/arch_packaging_standards
> Package naming
> 
> Package names can contain only alphanumeric characters and any of @, ., _, +, -. Names are not allowed to start with hyphens or dots. All letters should be lowercase.

**Comment by gino0631** [comment]
The requirement in the quotation is for names, not versions. Uppercase letters are not forbidden in package versions:
> Versions can include letters if need be (eg, nmap's version is 2.54BETA32)
